apiVersion: managed.openshift.io/v1alpha1
kind: SubjectPermission
metadata:
  name: rhoam-cs-sre-admin
  namespace: openshift-rbac-permissions
spec:
  clusterPermissions:
  - dedicated-admins-cluster
  - layered-cs-sre-admin-cluster
  permissions:
  - allowFirst: true
    clusterRoleName: rhoam-cs-sre-admin-project
    namespacesAllowedRegex: (^redhat-rhoam$|^redhat-rhoam-.*)
  subjectKind: Group
  subjectName: rhoam-cs-sre-admins  